[package]
name = "eventmgr-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"

[[bin]]
name = "event_mgr"
path = "src/main.rs"

[lib]
name = "event_mgr"
path = "src/lib/lib.rs"
